SECRET_PATH: "conf/.secrets.yaml"
# Default environment. Overridden if specified through environment variable.
TARGET_ENV: "uat"
API_KEY_HEADER: "Ocp-Apim-Subscription-Key"
BASE_URL: "http://quotes.toscrape.com/"