dev:
  username: <USERNAME_DEV>
  password: <PASSWORD_DEV>
  selfcare:
    username: <USERNAME_SELFCARE_DEV>
    password: <PASSWORD_SELFCARE_DEV>

uat:
  username: <USERNAME_UAT>
  password: <PASSWORD_UAT>
  selfcare:
    username: <USERNAME_SELFCARE_UAT>
    password: <PASSWORD_SELFCARE_UAT>
